### ISSUE TITLE
Add typing for the i18n next labels

### ISSUE THREAD

**Issue by nantvermeulen** [ioulian/next-io-ghent-starter#1]
It's possible to add typechecking for the i18n labels. You just need to define which files that should be used for type checking.
Example: [mijnenergie-kbc]( https://bitbucket.org/persgroep/mijnenergie-kbc/src/cea2b1149fbca15f617abad9941837ac03cfe724/frontend/i18n-resources.d.ts)
In mijnenergie-kbc I also added a [node script](https://bitbucket.org/persgroep/mijnenergie-kbc/src/4ce08edd870535de8a5aee4b28c8b090c2126ba9/frontend/checkTranslations.js) which checks if the translation files aren't missing any keys. This script is currently for just 2 languages but could be easily expanded based on the needs.

**Comment by ioulian** [comment]
Has been implemented
