### ISSUE TITLE
ButtonGroup component: make sure visual order matches DOM order

### ISSUE THREAD

**Issue by timdujardin** [ioulian/next-io-ghent-starter#24]
https://developer.mozilla.org/en-US/docs/Web/CSS/flex-direction#accessibility_concerns

`flex-direction: ${({ $alignRight }) => ($alignRight ? "row-reverse" : "row")};`

The buttons inside the group should effectively be reordered semantically and not only visually, as a rule of thumb we should prevent using `row-reverse` and `column-reverse` since it breaks visual and DOM connection.

**Comment by ioulian** [comment]
fixed in b212ed5f7783ce1d97ed533fac8f7dbe14eecc8e
