### ISSUE TITLE
Add styled props helper

### ISSUE THREAD

**Issue by ioulian** [ioulian/next-io-ghent-starter#8]
import { ComponentProps } from "react";
import {
  StyledComponentInnerComponent,
  StyledComponentInnerOtherProps,
  AnyStyledComponent,
  StyledComponentPropsWithRef,
} from "styled-components";

export type inferStyledTypes<T extends AnyStyledComponent> = ComponentProps<
  StyledComponentInnerComponent<T>
> &
  StyledComponentInnerOtherProps<T> &
  StyledComponentPropsWithRef<T>;

**Comment by ioulian** [comment]
Better:

`import { ComponentPropsWithoutRef, JSXElementConstructor } from "react";
import {
  AnyStyledComponent,
  StyledComponentInnerComponent,
  StyledComponentInnerOtherProps,
} from "styled-components";

export type InferStyledComponentProps<T> = T extends AnyStyledComponent
  ? ComponentPropsWithoutRef<StyledComponentInnerComponent<T>> &
      StyledComponentInnerOtherProps<T>
  : // eslint-disable-next-line no-undef
  T extends keyof JSX.IntrinsicElements | JSXElementConstructor<any>
  ? ComponentPropsWithoutRef<T>
  : never;
`

**Comment by ioulian** [comment]
InferStyledComponentProps -> InferComponentProps

**Comment by timdujardin** [comment]
Fixed in https://github.com/ioulian/next-io-ghent-starter/commit/6ace95548dcd9deab3facd513d415cf1835234dc.
